package com.paymentgateway.settlement.common;

import com.paymentgateway.settlement.api.dto.ApiError;
import com.paymentgateway.settlement.api.dto.ValidationError;
import com.paymentgateway.settlement.domain.idempotency.IdempotencyKeyConflictException;
import com.paymentgateway.settlement.domain.payment.IllegalStateTransitionException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

import jakarta.servlet.http.HttpServletRequest;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

/**
 * Global exception handler — translates domain/infrastructure exceptions
 * into structured {@link ApiError} responses.
 *
 * <p><strong>Correlation ID policy:</strong> Every error response uses the
 * same correlation ID that the client supplied (or that was generated by
 * {@code CorrelationIdFilter} for the request). This keeps the response
 * header and response body consistent so a client can correlate errors
 * with server-side logs.</p>
 *
 * <p><strong>Security:</strong> Stack traces and database error messages
 * are never exposed to API clients. Detailed technical causes are logged
 * with the correlation ID (via MDC) but only the error code and a
 * human-readable message are returned.</p>
 */
@RestControllerAdvice
public class PaymentGatewayExceptionHandler {

    private static final Logger log = LoggerFactory.getLogger(PaymentGatewayExceptionHandler.class);

    private static final DateTimeFormatter TS_FORMATTER =
            DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ssZ").withZone(ZoneOffset.UTC);

    /**
     * Resolves the correlation ID for an error response.
     *
     * <p>Priority: use the client-supplied {@code X-Correlation-Id} header
     * if present and valid; otherwise generate a new UUID. This matches
     * the policy in {@code CorrelationIdFilter} so the response header and
     * response body always agree.</p>
     */
    private static String resolveCorrelationId(final HttpServletRequest request) {
        String header = request.getHeader("X-Correlation-Id");
        if (header != null && !header.isBlank()) {
            try {
                UUID.fromString(header);
                return header;
            } catch (IllegalArgumentException e) {
                // Malformed header — generate a new UUID.
            }
        }
        return UUID.randomUUID().toString();
    }

    @ExceptionHandler({IllegalArgumentException.class, IllegalStateException.class})
    public ResponseEntity<ApiError> handleBadRequest(
            final RuntimeException ex, final HttpServletRequest request) {

        String correlationId = resolveCorrelationId(request);

        return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(new ApiError(
                        Instant.now().getEpochSecond(),
                        HttpStatus.BAD_REQUEST.value(),
                        "INVALID_REQUEST",
                        ex.getMessage(),
                        request.getRequestURI(),
                        null,
                        correlationId
                ));
    }

    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<ApiError> handleValidation(
            final MethodArgumentNotValidException ex, final HttpServletRequest request) {

        List<ValidationError> errors = ex.getBindingResult().getFieldErrors().stream()
                .map(fe -> new ValidationError(fe.getField(), fe.getDefaultMessage()))
                .collect(Collectors.toList());

        String correlationId = resolveCorrelationId(request);

        return ResponseEntity.status(HttpStatus.BAD_REQUEST)
                .body(new ApiError(
                        Instant.now().getEpochSecond(),
                        HttpStatus.BAD_REQUEST.value(),
                        "VALIDATION_FAILED",
                        "Request validation failed",
                        request.getRequestURI(),
                        errors,
                        correlationId
                ));
    }

    @ExceptionHandler(jakarta.persistence.EntityNotFoundException.class)
    public ResponseEntity<ApiError> handleNotFound(
            final jakarta.persistence.EntityNotFoundException ex, final HttpServletRequest request) {

        String correlationId = resolveCorrelationId(request);

        return ResponseEntity.status(HttpStatus.NOT_FOUND)
                .body(new ApiError(
                        Instant.now().getEpochSecond(),
                        HttpStatus.NOT_FOUND.value(),
                        "NOT_FOUND",
                        ex.getMessage(),
                        request.getRequestURI(),
                        null,
                        correlationId
                ));
    }

    @ExceptionHandler(IllegalStateTransitionException.class)
    public ResponseEntity<ApiError> handleStateTransition(
            final IllegalStateTransitionException ex, final HttpServletRequest request) {

        String correlationId = resolveCorrelationId(request);

        return ResponseEntity.status(HttpStatus.CONFLICT)
                .body(new ApiError(
                        Instant.now().getEpochSecond(),
                        HttpStatus.CONFLICT.value(),
                        "ILLEGAL_STATE_TRANSITION",
                        ex.getMessage(),
                        request.getRequestURI(),
                        null,
                        correlationId
                ));
    }

    /**
     * Handles idempotency key conflicts: the same key was reused with a
     * different request payload.
     *
     * <p><strong>Why 409 CONFLICT:</strong> The caller did nothing wrong in
     * isolation — the conflict is with a *prior concurrent* request. 409
     * lets the caller distinguish "fix your payload" from "retry later /
     * use the original key".</p>
     */
    @ExceptionHandler(IdempotencyKeyConflictException.class)
    public ResponseEntity<ApiError> handleIdempotencyConflict(
            final IdempotencyKeyConflictException ex, final HttpServletRequest request) {
        String correlationId = resolveCorrelationId(request);

        log.warn("Idempotency conflict: key={}, existingPaymentId={}, correlationId={}",
                ex.getIdempotencyKey(), ex.getExistingPaymentId(), correlationId);

        return ResponseEntity.status(HttpStatus.CONFLICT)
                .body(new ApiError(
                        Instant.now().getEpochSecond(),
                        HttpStatus.CONFLICT.value(),
                        "IDEMPOTENCY_KEY_CONFLICT",
                        ex.getMessage(),
                        request.getRequestURI(),
                        null,
                        correlationId
                ));
    }

    /**
     * Handles optimistic-locking failures during state transitions.
     *
     * <p><strong>Why 409 CONFLICT:</strong> The state transition could not
     * complete because another worker modified the row first. The caller
     * should retry the request (the idempotency key makes this safe).</p>
     */
    @ExceptionHandler(org.springframework.orm.ObjectOptimisticLockingFailureException.class)
    public ResponseEntity<ApiError> handleOptimisticLock(
            final org.springframework.orm.ObjectOptimisticLockingFailureException ex,
            final HttpServletRequest request) {
        String correlationId = resolveCorrelationId(request);

        log.warn("Optimistic locking conflict: correlationId={}", correlationId);

        return ResponseEntity.status(HttpStatus.CONFLICT)
                .body(new ApiError(
                        Instant.now().getEpochSecond(),
                        HttpStatus.CONFLICT.value(),
                        "OPTIMISTIC_LOCK_CONFLICT",
                        "State transition conflict; please retry",
                        request.getRequestURI(),
                        null,
                        correlationId
                ));
    }

    @ExceptionHandler(Exception.class)
    public ResponseEntity<ApiError> handleUnexpected(
            final Exception ex, final HttpServletRequest request) {

        String correlationId = resolveCorrelationId(request);

        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                .body(new ApiError(
                        Instant.now().getEpochSecond(),
                        HttpStatus.INTERNAL_SERVER_ERROR.value(),
                        "INTERNAL_ERROR",
                        "An unexpected error occurred. Reference: " + correlationId,
                        request.getRequestURI(),
                        null,
                        correlationId
                ));
    }
}
